name: Go
on: [push, pull_request]
env:
  GO_VERSION: "1.20"
jobs:

  build:
    name: Build
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repo
        uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608

      - name: "Install Go ${{env.GO_VERSION}}"
        uses: actions/setup-go@0c52d547c9bc32b1aa3301fd7a9cb496313a4491
        with:
          go-version: "${{env.GO_VERSION}}"

      - name: Install Ginkgo CLI
        run: |
          go install github.com/onsi/ginkgo/v2/ginkgo@latest

      - name: Run tests
        run: |
          make test
